// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Authorize(arg1:string):Promise<boolean>;

export function GetAuthStatus():Promise<Record<string, any>>;

export function GetBetTypeAliases():Promise<backend.BetTypeAliases>;

export function GetColorConfig():Promise<backend.ColorConfig>;

export function GetKeywordAliases():Promise<backend.KeywordAliases>;

export function GetOddsConfig():Promise<backend.OddsConfig>;

export function GetSystemConfig():Promise<backend.SystemConfig>;

export function GetTailConfig():Promise<backend.TailConfig>;

export function GetZodiacConfig():Promise<backend.ZodiacConfig>;

export function IsAuthorized():Promise<boolean>;

export function ParseBetInput(arg1:string,arg2:Array<string>):Promise<backend.BetParseResponse>;

export function ParseBetInputIntelligent(arg1:string,arg2:Array<string>):Promise<backend.BetParsingResult>;

export function ResetSystemConfig():Promise<void>;

export function SaveBetTypeAliases(arg1:backend.BetTypeAliases):Promise<void>;

export function SaveColorConfig(arg1:backend.ColorConfig):Promise<void>;

export function SaveKeywordAliases(arg1:backend.KeywordAliases):Promise<void>;

export function SaveOddsConfig(arg1:backend.OddsConfig):Promise<void>;

export function SaveTailConfig(arg1:backend.TailConfig):Promise<void>;

export function SaveZodiacConfig(arg1:backend.ZodiacConfig):Promise<void>;
