// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authorize(arg1) {
  return window['go']['backend']['App']['Authorize'](arg1);
}

export function GetAuthStatus() {
  return window['go']['backend']['App']['GetAuthStatus']();
}

export function GetBetTypeAliases() {
  return window['go']['backend']['App']['GetBetTypeAliases']();
}

export function GetColorConfig() {
  return window['go']['backend']['App']['GetColorConfig']();
}

export function GetKeywordAliases() {
  return window['go']['backend']['App']['GetKeywordAliases']();
}

export function GetOddsConfig() {
  return window['go']['backend']['App']['GetOddsConfig']();
}

export function GetSystemConfig() {
  return window['go']['backend']['App']['GetSystemConfig']();
}

export function GetTailConfig() {
  return window['go']['backend']['App']['GetTailConfig']();
}

export function GetZodiacConfig() {
  return window['go']['backend']['App']['GetZodiacConfig']();
}

export function IsAuthorized() {
  return window['go']['backend']['App']['IsAuthorized']();
}

export function ParseBetInput(arg1, arg2) {
  return window['go']['backend']['App']['ParseBetInput'](arg1, arg2);
}

export function ParseBetInputIntelligent(arg1, arg2) {
  return window['go']['backend']['App']['ParseBetInputIntelligent'](arg1, arg2);
}

export function ResetSystemConfig() {
  return window['go']['backend']['App']['ResetSystemConfig']();
}

export function SaveBetTypeAliases(arg1) {
  return window['go']['backend']['App']['SaveBetTypeAliases'](arg1);
}

export function SaveColorConfig(arg1) {
  return window['go']['backend']['App']['SaveColorConfig'](arg1);
}

export function SaveKeywordAliases(arg1) {
  return window['go']['backend']['App']['SaveKeywordAliases'](arg1);
}

export function SaveOddsConfig(arg1) {
  return window['go']['backend']['App']['SaveOddsConfig'](arg1);
}

export function SaveTailConfig(arg1) {
  return window['go']['backend']['App']['SaveTailConfig'](arg1);
}

export function SaveZodiacConfig(arg1) {
  return window['go']['backend']['App']['SaveZodiacConfig'](arg1);
}
